// Mock dataset of realistic Kenyan businesses for the KHC-DE Discovery Engine.
// Includes raw duplicate items and various indicators (VC funded, local reviews, branches) to test all modules.

const mockCompanies = [
  {
    name: "Top Image Africa Ltd",
    sector: "Branding & Marketing",
    city: "Nairobi",
    county: "Nairobi",
    website: "https://topimageafrica.com",
    phone: "+254722112233",
    source: "Google Maps",
    founder_name: "Harriet Kabibi",
    email: "harriet@topimageafrica.com",
    founded_year: 2008,
    reviews: 4.8,
    branches: 3,
    employees: 85,
    exports: true,
    growth_signal: 8,
    // Ecosystem indicators (Not VC funded, invisible)
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Top Image Africa",
    sector: "Branding & Marketing",
    city: "Nairobi",
    county: "Nairobi",
    website: "http://topimageafrica.com",
    phone: "+254 722 112233",
    source: "Yellow Pages Kenya",
    founder_name: "Harriet Kabibi",
    email: "harriet@topimage.com",
    founded_year: 2008,
    reviews: 4.6,
    branches: 3,
    employees: 80,
    exports: true,
    growth_signal: 7,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Top Image",
    sector: "Branding & Marketing",
    city: "Nairobi",
    county: "Nairobi",
    website: "",
    phone: "0722112233",
    source: "Bizna Kenya",
    founder_name: "H. Kabibi",
    email: "",
    founded_year: 2008,
    reviews: 4.7,
    branches: 1,
    employees: 85,
    exports: false,
    growth_signal: 6,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Kipeto Waste Processors",
    sector: "Waste Management",
    city: "Kajiado",
    county: "Kajiado",
    website: "https://kipetowaste.co.ke",
    phone: "+254711889900",
    source: "Google Maps",
    founder_name: "John Kiprono",
    email: "jkiprono@kipetowaste.co.ke",
    founded_year: 2017,
    reviews: 4.5,
    branches: 2,
    employees: 40,
    exports: false,
    growth_signal: 7,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Kipeto Waste Solutions",
    sector: "Waste Management",
    city: "Kajiado",
    county: "Kajiado",
    website: "https://kipetowaste.co.ke",
    phone: "0711889900",
    source: "PPRA Procurement",
    founder_name: "John Kiprono",
    email: "info@kipetowaste.co.ke",
    founded_year: 2017,
    reviews: 4.4,
    branches: 2,
    employees: 42,
    exports: false,
    growth_signal: 8,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Equator Agro Processors",
    sector: "Agro-processing",
    city: "Meru",
    county: "Meru",
    website: "https://equatoragro.com",
    phone: "+254701223344",
    source: "Kenya Association of Manufacturers",
    founder_name: "Phyllis Mureithi",
    email: "phyllis@equatoragro.com",
    founded_year: 2012,
    reviews: 4.9,
    branches: 4,
    employees: 120,
    exports: true,
    growth_signal: 9,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Thika Animal Feeds",
    sector: "Animal Feed Manufacturer",
    city: "Thika",
    county: "Kiambu",
    website: "https://thikaanimalfeeds.co.ke",
    phone: "+254733445566",
    source: "Google Maps",
    founder_name: "James Kuria",
    email: "kuria@thikaanimalfeeds.co.ke",
    founded_year: 2005,
    reviews: 4.7,
    branches: 5,
    employees: 150,
    exports: false,
    growth_signal: 8,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Thika Feeds",
    sector: "Animal Feed Manufacturer",
    city: "Thika",
    county: "Kiambu",
    website: "",
    phone: "0733445566",
    source: "Yellow Pages Kenya",
    founder_name: "J. Kuria",
    email: "info@thikafeeds.com",
    founded_year: 2006,
    reviews: 4.2,
    branches: 1,
    employees: 140,
    exports: false,
    growth_signal: 7,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Pwani Packaging Solutions",
    sector: "Packaging",
    city: "Mombasa",
    county: "Mombasa",
    website: "https://pwanipackaging.co.ke",
    phone: "+254720998877",
    source: "Kenya Association of Manufacturers",
    founder_name: "Said Athman",
    email: "said.athman@pwanipackaging.co.ke",
    founded_year: 2015,
    reviews: 4.4,
    branches: 2,
    employees: 65,
    exports: true,
    growth_signal: 6,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Naivasha Horticulture Ltd",
    sector: "Agro-processing",
    city: "Naivasha",
    county: "Nakuru",
    website: "https://naivashahort.com",
    phone: "+254705554433",
    source: "Fresh Produce Exporters Association",
    founder_name: "Sarah Wanjiku",
    email: "swanjiku@naivashahort.com",
    founded_year: 2010,
    reviews: 4.8,
    branches: 3,
    employees: 210,
    exports: true,
    growth_signal: 9,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  // Famous startups (Should score high on visibility, meaning NOT a hidden champion)
  {
    name: "Twiga Foods",
    sector: "Agro-processing",
    city: "Nairobi",
    county: "Nairobi",
    website: "https://twigafoods.com",
    phone: "+254709258000",
    source: "Google Maps",
    founder_name: "Peter Njonjo",
    email: "info@twigafoods.com",
    founded_year: 2014,
    reviews: 4.5,
    branches: 6,
    employees: 400,
    exports: false,
    growth_signal: 8,
    // VC funded and accelerator alumnus, highly visible!
    is_vc_funded: true,
    is_accelerator_alumnus: true,
    media_mentions: true,
  },
  {
    name: "Copias Kenya (Copia)",
    sector: "E-Commerce Logistics",
    city: "Nairobi",
    county: "Nairobi",
    website: "https://copia.co.ke",
    phone: "+254709070000",
    source: "TechCabal News",
    founder_name: "Tracey Turner",
    email: "info@copia.co.ke",
    founded_year: 2013,
    reviews: 4.2,
    branches: 12,
    employees: 500,
    exports: false,
    growth_signal: 7,
    is_vc_funded: true,
    is_accelerator_alumnus: true,
    media_mentions: true,
  },
  // Emerging champions
  {
    name: "Maka Water Filters",
    sector: "Manufacturing",
    city: "Kisumu",
    county: "Kisumu",
    website: "https://makafilters.co.ke",
    phone: "+254712345678",
    source: "Bizna Kenya",
    founder_name: "Alice Omondi",
    email: "alice@makafilters.co.ke",
    founded_year: 2020,
    reviews: 4.6,
    branches: 1,
    employees: 18,
    exports: false,
    growth_signal: 9,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  },
  {
    name: "Savannah Engineering Works",
    sector: "Industrial supplier",
    city: "Athi River",
    county: "Machakos",
    website: "https://savannaheng.com",
    phone: "+254780556677",
    source: "Google Maps",
    founder_name: "Daniel Musembi",
    email: "dmusembi@savannaheng.com",
    founded_year: 1998,
    reviews: 4.8,
    branches: 2,
    employees: 95,
    exports: true,
    growth_signal: 7,
    is_vc_funded: false,
    is_accelerator_alumnus: false,
    media_mentions: false,
  }
];

function simulateSearch(query) {
  // Return a subset of the mock data matching the query or sector, or just return random subset
  const q = query.toLowerCase();
  const filtered = mockCompanies.filter(c => 
    c.name.toLowerCase().includes(q) || 
    c.sector.toLowerCase().includes(q) ||
    c.city.toLowerCase().includes(q)
  );

  // If no direct matches, return a slice of 4 to 8 companies to simulate scraping
  if (filtered.length === 0) {
    const start = Math.floor(Math.random() * (mockCompanies.length - 5));
    return mockCompanies.slice(start, start + 6);
  }
  return filtered;
}

module.exports = {
  mockCompanies,
  simulateSearch
};
